"""Markdown rendering of the per-gate behaviour record (URS-W1-031).

Deterministic output — no timestamps, no absolute paths — so a diff always means a verdict
changed.
"""

from __future__ import annotations

from .model import VERDICT_DIVERGENCE, GateVerdict


def _cell(value: str) -> str:
	return value.replace("|", "\\|").replace("\n", " ")


def render_markdown(wave: str, verdicts: tuple[GateVerdict, ...]) -> str:
	divergences = [verdict for verdict in verdicts if verdict.verdict == VERDICT_DIVERGENCE]
	lines: list[str] = [
		f"# Wave {wave} — per-gate behaviour record",
		"",
		"Generated by `python -m tools.behaviour.generate --wave "
		f"{wave}` from executed characterisation contracts and the test suite's test-case "
		"citations (URS-W1-031). Do not edit by hand — regenerate.",
		"",
		f"{len(verdicts)} gates: {len(verdicts) - len(divergences)} parity, "
		f"{len(divergences)} intentional divergence.",
		"",
		"| Gate | URS | Legacy baseline | Verdict | Evidence | Sign-off |",
		"|---|---|---|---|---|---|",
	]
	for verdict in verdicts:
		lines.append(
			"| "
			+ " | ".join(
				[
					_cell(verdict.gate.name),
					", ".join(verdict.gate.urs_ids),
					f"`{_cell(verdict.gate.legacy_source)}`",
					f"**{verdict.verdict}**" if verdict.verdict == VERDICT_DIVERGENCE else verdict.verdict,
					_cell(verdict.detail),
					_cell(f"{verdict.decision}: {verdict.sign_off}") if verdict.sign_off else "—",
				]
			)
			+ " |"
		)
	lines.extend(["", "## Verdict sources", ""])
	lines.append(
		"* **contract** — the gate's parity contract was executed over its committed fixtures; "
		"a failure without a signed-off divergence aborts generation."
	)
	lines.append(
		"* **anchor-adopt** — behaviour adopted from the substrate with no Qcadoo baseline; the "
		"verdict is the mapped test case's citation in the suite."
	)
	lines.append("")
	for verdict in divergences:
		lines.extend(
			[
				f"### {verdict.gate.name} — intentional divergence",
				"",
				f"* Decision: **{verdict.decision}**",
				f"* Sign-off: {verdict.sign_off}",
				f"* Delta: {verdict.detail}",
				"",
			]
		)
	return "\n".join(lines).rstrip() + "\n"
