"""Markdown rendering of an evidence pack (URS-W0-013).

Output is deterministic — no timestamps, no absolute paths — so regenerating the pack on a
clean checkout produces a byte-identical file and a diff always means the evidence changed.
"""

from __future__ import annotations

from .model import STATUS_COMPLETE, STATUS_INCOMPLETE, STATUS_UNLINKED, EvidenceRow, Report

STATUS_LABEL = {
	STATUS_COMPLETE: "complete",
	STATUS_INCOMPLETE: "**evidence-incomplete**",
	STATUS_UNLINKED: "**unlinked**",
}


def _cell(value: str) -> str:
	return value.replace("|", "\\|").replace("\n", " ")


def _join(values: tuple[str, ...]) -> str:
	return ", ".join(values) if values else "—"


#: Verifying tests listed per test case before the cell is summarised.
MAX_LOCATIONS_PER_TC = 3


def _locations_cell(locations: tuple[str, ...]) -> str:
	shown = ", ".join(f"`{location}`" for location in locations[:MAX_LOCATIONS_PER_TC])
	remaining = len(locations) - MAX_LOCATIONS_PER_TC
	return f"{shown} (+{remaining} more)" if remaining > 0 else shown


def _evidence_cell(row: EvidenceRow) -> str:
	if not row.evidence:
		return "—"
	parts = [f"{tc_id}: {_locations_cell(locations)}" for tc_id, locations in row.evidence.items()]
	return "<br>".join(parts)


def render_markdown(report: Report) -> str:
	lines: list[str] = []
	lines.append(f"# Wave {report.wave} — evidence pack")
	lines.append("")
	lines.append(
		"Auto-generated by `python -m tools.evidence.generate --wave "
		f"{report.wave}` (W0-7, URS-W0-013). **Do not edit by hand** — regenerate instead."
	)
	lines.append("")
	lines.append("Sources of truth read for this pack:")
	lines.append("")
	lines.append(f"- backlog + dossier citations: `{report.sources['backlog']}`")
	lines.append(f"- requirements: `{report.sources['urs']}`")
	lines.append(f"- test cases + traceability matrix: `{report.sources['tst']}`")
	lines.append(
		"- evidence: docstring citations in `tests/**` and the register `docs/evidence/manual-evidence.md`"
	)
	lines.append("")
	lines.append("## 1. Summary")
	lines.append("")
	lines.append("| Backlog items | complete | evidence-incomplete | unlinked |")
	lines.append("|---|---|---|---|")
	lines.append(
		f"| {len(report.rows)} | {len(report.complete)} | {len(report.incomplete)} | {len(report.unlinked)} |"
	)
	lines.append("")
	if report.unlinked:
		lines.append(
			"> **Audit spine broken:** "
			+ ", ".join(row.backlog.id for row in report.unlinked)
			+ " have no URS→TC link. The generator exits non-zero until this is fixed."
		)
		lines.append("")
	if report.incomplete:
		lines.append(
			"> **Evidence incomplete (reported, not omitted):** "
			+ ", ".join(row.backlog.id for row in report.incomplete)
			+ ". Re-run the generator once the implementing tests land."
		)
		lines.append("")
	lines.append("## 2. Traceability — item → dossier finding → URS → test cases")
	lines.append("")
	lines.append("| # | Item | Disposition | Dossier finding (evidence) | URS | Test cases | Status |")
	lines.append("|---|---|---|---|---|---|---|")
	for row in report.rows:
		lines.append(
			"| {id} | {item} | {disposition} | {dossier} | {urs} | {tcs} | {status} |".format(
				id=row.backlog.id,
				item=_cell(row.backlog.item),
				disposition=_cell(row.backlog.disposition) or "—",
				dossier=_cell(row.backlog.dossier_citation) or "—",
				urs=_join(row.urs_ids),
				tcs=_join(row.tc_ids),
				status=STATUS_LABEL[row.status],
			)
		)
	lines.append("")
	lines.append("## 3. Evidence per backlog item")
	lines.append("")
	lines.append("| # | Test case → verifying test(s) | Missing evidence | Notes |")
	lines.append("|---|---|---|---|")
	for row in report.rows:
		lines.append(
			"| {id} | {evidence} | {missing} | {notes} |".format(
				id=row.backlog.id,
				evidence=_evidence_cell(row),
				missing=_join(row.missing_tc_ids),
				notes=_cell("; ".join(row.notes)) or "—",
			)
		)
	lines.append("")
	lines.append("## 4. Requirements covered")
	lines.append("")
	lines.append("| URS | Title | Backlog item |")
	lines.append("|---|---|---|")
	for row in report.rows:
		for urs_id in row.urs_ids:
			title = report.urs_titles.get(urs_id, "")
			lines.append(f"| {urs_id} | {_cell(title)} | {row.backlog.id} |")
	lines.append("")
	return "\n".join(lines)
